### ISSUE TITLE
Enhancement: Add CMake checks for C++11 features that Infector++ requires

### ISSUE THREAD

**Issue by ViteFalcon** [Darelbi/Infectorpp#8]
Currently, Infector++'s CMake scripts don't check the compiler to make sure that the required features are met. There a few solutions out there to do the checks in CMake. Here's a couple.
1. [CMake Compile Features](http://www.cmake.org/cmake/help/v3.1/manual/cmake-compile-features.7.html)
2. [C++11 Detection in CMake](http://pageant.ghulbus.eu/?p=664): This is a bit involved though, since you'll need a folder that contains C++11 code that contains the specific feature that you'd require.

**Comment by Darelbi** [comment]
It is a very good idea so that people is aware that eventual compile errors are fault of their compiler (tipically Visual Studio XD) and not of the library. Compiling a list of features for version1 can be a bit long (I used plenty of them when I designed it), maybe I'll do that for version2 wich is slightly more backward compatible.

**Comment by Darelbi** [comment]
leveraged to continuos integration servers now
